// generated by the following code:
//
const gradient = require('gradient-string');
//
// Use the output directly here to keep the bundle small.

const banner = gradient([
  { color: '#42d392', pos: 0 },
  { color: '#42d392', pos: 0.1 },
  { color: '#647eff', pos: 1 }
])('Hello world! - Whale FE');

export default banner;
